// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"net/http"
)

type CreateStepRequest struct {
	StepAPICreateIn shared.StepAPICreateIn `request:"mediaType=application/json"`
}

func (o *CreateStepRequest) GetStepAPICreateIn() shared.StepAPICreateIn {
	if o == nil {
		return shared.StepAPICreateIn{}
	}
	return o.StepAPICreateIn
}

type CreateStepResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	StepAPIOut *shared.StepAPIOut
}

func (o *CreateStepResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateStepResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateStepResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateStepResponse) GetStepAPIOut() *shared.StepAPIOut {
	if o == nil {
		return nil
	}
	return o.StepAPIOut
}
