// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"net/http"
)

type CreateWorkflowMapRequest struct {
	WorkflowMapAPICreateIn shared.WorkflowMapAPICreateIn `request:"mediaType=application/json"`
}

func (o *CreateWorkflowMapRequest) GetWorkflowMapAPICreateIn() shared.WorkflowMapAPICreateIn {
	if o == nil {
		return shared.WorkflowMapAPICreateIn{}
	}
	return o.WorkflowMapAPICreateIn
}

type CreateWorkflowMapResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	WorkflowMapAPIOut *shared.WorkflowMapAPIOut
}

func (o *CreateWorkflowMapResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *CreateWorkflowMapResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *CreateWorkflowMapResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *CreateWorkflowMapResponse) GetWorkflowMapAPIOut() *shared.WorkflowMapAPIOut {
	if o == nil {
		return nil
	}
	return o.WorkflowMapAPIOut
}
