// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"net/http"
)

type DeleteWorkflowRequest struct {
	// The unique ID of the workflow
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *DeleteWorkflowRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type DeleteWorkflowResponse struct {
	// OK
	AppActionResponse *shared.AppActionResponse
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *DeleteWorkflowResponse) GetAppActionResponse() *shared.AppActionResponse {
	if o == nil {
		return nil
	}
	return o.AppActionResponse
}

func (o *DeleteWorkflowResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *DeleteWorkflowResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *DeleteWorkflowResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
