// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"net/http"
)

type GetAPITokenSecurity struct {
	Password string `security:"scheme,type=http,subtype=basic,name=password"`
	Username string `security:"scheme,type=http,subtype=basic,name=username"`
}

func (o *GetAPITokenSecurity) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *GetAPITokenSecurity) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}

type GetAPITokenRequest struct {
}

type GetAPITokenResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	LegacyAPITokenOut *shared.LegacyAPITokenOut
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *GetAPITokenResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *GetAPITokenResponse) GetLegacyAPITokenOut() *shared.LegacyAPITokenOut {
	if o == nil {
		return nil
	}
	return o.LegacyAPITokenOut
}

func (o *GetAPITokenResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *GetAPITokenResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
