// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"net/http"
)

type ReadWorkflowMapRequest struct {
	// The unique ID of the workflow map
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ReadWorkflowMapRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ReadWorkflowMapResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	WorkflowMapAPIOut *shared.WorkflowMapAPIOut
}

func (o *ReadWorkflowMapResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReadWorkflowMapResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReadWorkflowMapResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *ReadWorkflowMapResponse) GetWorkflowMapAPIOut() *shared.WorkflowMapAPIOut {
	if o == nil {
		return nil
	}
	return o.WorkflowMapAPIOut
}
