// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"github.com/speakeasy-sdks/risk-go/pkg/utils"
	"net/http"
)

type ReadAllRecordsRequest struct {
	// The unique ID of an application where, if provided, the response will only contain records from the identified application
	ApplicationID *string `default:"" queryParam:"style=form,explode=true,name=application-id"`
	// The zero-indexed page number (must not be less than 0, defaults to 0)
	Page *int `queryParam:"style=form,explode=true,name=page"`
	// The size of the page and maximum number of items to be returned (must not be less than 1, defaults to 20)
	Size *int `queryParam:"style=form,explode=true,name=size"`
	// The unique ID of a step where, if provided, the response will only contain records on the identified step
	StepID *string `default:"" queryParam:"style=form,explode=true,name=step-id"`
	// A timestamp measured in milliseconds since the Unix epoch where, if provided, the response will only contain records that have been modified since the given timestamp
	UpdatedMin *int64 `queryParam:"style=form,explode=true,name=updated-min"`
	// The unique ID of a workflow where, if provided, the response will only contain records from the identified workflow
	WorkflowID *string `default:"" queryParam:"style=form,explode=true,name=workflow-id"`
}

func (r ReadAllRecordsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(r, "", false)
}

func (r *ReadAllRecordsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &r, "", false, false); err != nil {
		return err
	}
	return nil
}

func (o *ReadAllRecordsRequest) GetApplicationID() *string {
	if o == nil {
		return nil
	}
	return o.ApplicationID
}

func (o *ReadAllRecordsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ReadAllRecordsRequest) GetSize() *int {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *ReadAllRecordsRequest) GetStepID() *string {
	if o == nil {
		return nil
	}
	return o.StepID
}

func (o *ReadAllRecordsRequest) GetUpdatedMin() *int64 {
	if o == nil {
		return nil
	}
	return o.UpdatedMin
}

func (o *ReadAllRecordsRequest) GetWorkflowID() *string {
	if o == nil {
		return nil
	}
	return o.WorkflowID
}

type ReadAllRecordsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	PageModelOutRecordAPIOut *shared.PageModelOutRecordAPIOut
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ReadAllRecordsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReadAllRecordsResponse) GetPageModelOutRecordAPIOut() *shared.PageModelOutRecordAPIOut {
	if o == nil {
		return nil
	}
	return o.PageModelOutRecordAPIOut
}

func (o *ReadAllRecordsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReadAllRecordsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
