// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"net/http"
)

type ReadAllWorkflowMapsRequest struct {
	// The zero-indexed page number (must not be less than 0, defaults to 0)
	Page *int `queryParam:"style=form,explode=true,name=page"`
	// The size of the page and maximum number of items to be returned (must not be less than 1, defaults to 20)
	Size *int `queryParam:"style=form,explode=true,name=size"`
	// The unique ID of a workflow where, if provided, the response will only contain workflow maps from the identified workflow
	WorkflowID *string `queryParam:"style=form,explode=true,name=workflow-id"`
}

func (o *ReadAllWorkflowMapsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ReadAllWorkflowMapsRequest) GetSize() *int {
	if o == nil {
		return nil
	}
	return o.Size
}

func (o *ReadAllWorkflowMapsRequest) GetWorkflowID() *string {
	if o == nil {
		return nil
	}
	return o.WorkflowID
}

type ReadAllWorkflowMapsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	PageModelOutWorkflowMapAPIOut *shared.PageModelOutWorkflowMapAPIOut
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ReadAllWorkflowMapsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReadAllWorkflowMapsResponse) GetPageModelOutWorkflowMapAPIOut() *shared.PageModelOutWorkflowMapAPIOut {
	if o == nil {
		return nil
	}
	return o.PageModelOutWorkflowMapAPIOut
}

func (o *ReadAllWorkflowMapsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReadAllWorkflowMapsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
