// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"net/http"
)

type ReadAllApplicationsRequest struct {
	// The zero-indexed page number (must not be less than 0, defaults to 0)
	Page *int `queryParam:"style=form,explode=true,name=page"`
	// The size of the page and maximum number of items to be returned (must not be less than 1, defaults to 20)
	Size *int `queryParam:"style=form,explode=true,name=size"`
}

func (o *ReadAllApplicationsRequest) GetPage() *int {
	if o == nil {
		return nil
	}
	return o.Page
}

func (o *ReadAllApplicationsRequest) GetSize() *int {
	if o == nil {
		return nil
	}
	return o.Size
}

type ReadAllApplicationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// OK
	PageModelOutApplicationAPIOut *shared.PageModelOutApplicationAPIOut
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ReadAllApplicationsResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReadAllApplicationsResponse) GetPageModelOutApplicationAPIOut() *shared.PageModelOutApplicationAPIOut {
	if o == nil {
		return nil
	}
	return o.PageModelOutApplicationAPIOut
}

func (o *ReadAllApplicationsResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReadAllApplicationsResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
