// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"net/http"
)

type ReadApplicationRequest struct {
	// The unique ID of the application
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *ReadApplicationRequest) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type ReadApplicationResponse struct {
	// OK
	ApplicationAPIOut *shared.ApplicationAPIOut
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *ReadApplicationResponse) GetApplicationAPIOut() *shared.ApplicationAPIOut {
	if o == nil {
		return nil
	}
	return o.ApplicationAPIOut
}

func (o *ReadApplicationResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *ReadApplicationResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *ReadApplicationResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
