// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/risk-go/pkg/models/shared"
	"net/http"
)

type Update1Request struct {
	ApplicationAPIUpdateIn shared.ApplicationAPIUpdateIn `request:"mediaType=application/json"`
	// The unique ID of the application
	ID string `pathParam:"style=simple,explode=false,name=id"`
}

func (o *Update1Request) GetApplicationAPIUpdateIn() shared.ApplicationAPIUpdateIn {
	if o == nil {
		return shared.ApplicationAPIUpdateIn{}
	}
	return o.ApplicationAPIUpdateIn
}

func (o *Update1Request) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

type Update1Response struct {
	// OK
	ApplicationAPIOut *shared.ApplicationAPIOut
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
}

func (o *Update1Response) GetApplicationAPIOut() *shared.ApplicationAPIOut {
	if o == nil {
		return nil
	}
	return o.ApplicationAPIOut
}

func (o *Update1Response) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *Update1Response) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *Update1Response) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}
