// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type AppActionResponse struct {
	Action *string `json:"action,omitempty"`
	ID     *string `json:"id,omitempty"`
	Object *string `json:"object,omitempty"`
}

func (o *AppActionResponse) GetAction() *string {
	if o == nil {
		return nil
	}
	return o.Action
}

func (o *AppActionResponse) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *AppActionResponse) GetObject() *string {
	if o == nil {
		return nil
	}
	return o.Object
}
