// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PageModelOutApplicationAPIOut struct {
	// A array of returned items
	Content []ApplicationAPIOut `json:"content,omitempty"`
	// A collection of page URL links for navigation and iteration
	Links *PageLinksOut `json:"links,omitempty"`
	// A collection page metadata
	Page *PageInfoOut `json:"page,omitempty"`
}

func (o *PageModelOutApplicationAPIOut) GetContent() []ApplicationAPIOut {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *PageModelOutApplicationAPIOut) GetLinks() *PageLinksOut {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *PageModelOutApplicationAPIOut) GetPage() *PageInfoOut {
	if o == nil {
		return nil
	}
	return o.Page
}
