// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PageModelOutStepAPIOut struct {
	// A array of returned items
	Content []StepAPIOut `json:"content,omitempty"`
	// A collection of page URL links for navigation and iteration
	Links *PageLinksOut `json:"links,omitempty"`
	// A collection page metadata
	Page *PageInfoOut `json:"page,omitempty"`
}

func (o *PageModelOutStepAPIOut) GetContent() []StepAPIOut {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *PageModelOutStepAPIOut) GetLinks() *PageLinksOut {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *PageModelOutStepAPIOut) GetPage() *PageInfoOut {
	if o == nil {
		return nil
	}
	return o.Page
}
