// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PageModelOutWorkflowAPIOut struct {
	// A array of returned items
	Content []WorkflowAPIOut `json:"content,omitempty"`
	// A collection of page URL links for navigation and iteration
	Links *PageLinksOut `json:"links,omitempty"`
	// A collection page metadata
	Page *PageInfoOut `json:"page,omitempty"`
}

func (o *PageModelOutWorkflowAPIOut) GetContent() []WorkflowAPIOut {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *PageModelOutWorkflowAPIOut) GetLinks() *PageLinksOut {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *PageModelOutWorkflowAPIOut) GetPage() *PageInfoOut {
	if o == nil {
		return nil
	}
	return o.Page
}
