// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PageModelOutWorkflowMapAPIOut struct {
	// A array of returned items
	Content []WorkflowMapAPIOut `json:"content,omitempty"`
	// A collection of page URL links for navigation and iteration
	Links *PageLinksOut `json:"links,omitempty"`
	// A collection page metadata
	Page *PageInfoOut `json:"page,omitempty"`
}

func (o *PageModelOutWorkflowMapAPIOut) GetContent() []WorkflowMapAPIOut {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *PageModelOutWorkflowMapAPIOut) GetLinks() *PageLinksOut {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *PageModelOutWorkflowMapAPIOut) GetPage() *PageInfoOut {
	if o == nil {
		return nil
	}
	return o.Page
}
