// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type PageModelOutFieldAPIOut struct {
	// A array of returned items
	Content []FieldAPIOut `json:"content,omitempty"`
	// A collection of page URL links for navigation and iteration
	Links *PageLinksOut `json:"links,omitempty"`
	// A collection page metadata
	Page *PageInfoOut `json:"page,omitempty"`
}

func (o *PageModelOutFieldAPIOut) GetContent() []FieldAPIOut {
	if o == nil {
		return nil
	}
	return o.Content
}

func (o *PageModelOutFieldAPIOut) GetLinks() *PageLinksOut {
	if o == nil {
		return nil
	}
	return o.Links
}

func (o *PageModelOutFieldAPIOut) GetPage() *PageInfoOut {
	if o == nil {
		return nil
	}
	return o.Page
}
