// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SchemeBasic struct {
	Password string `security:"name=password"`
	Username string `security:"name=username"`
}

func (o *SchemeBasic) GetPassword() string {
	if o == nil {
		return ""
	}
	return o.Password
}

func (o *SchemeBasic) GetUsername() string {
	if o == nil {
		return ""
	}
	return o.Username
}
