// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type Security struct {
	Basic  *SchemeBasic `security:"scheme,type=http,subtype=basic"`
	Bearer *string      `security:"scheme,type=http,subtype=bearer,name=Authorization"`
}

func (o *Security) GetBasic() *SchemeBasic {
	if o == nil {
		return nil
	}
	return o.Basic
}

func (o *Security) GetBearer() *string {
	if o == nil {
		return nil
	}
	return o.Bearer
}
