// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// StepAPICreateInAssignableUserType - Indicates which users are allowed to be assigned this step on a record (defaults to APP_USERS)
type StepAPICreateInAssignableUserType string

const (
	StepAPICreateInAssignableUserTypeAppAndExternalUsers StepAPICreateInAssignableUserType = "APP_AND_EXTERNAL_USERS"
	StepAPICreateInAssignableUserTypeAppUsers            StepAPICreateInAssignableUserType = "APP_USERS"
	StepAPICreateInAssignableUserTypeExternalUsers       StepAPICreateInAssignableUserType = "EXTERNAL_USERS"
)

func (e StepAPICreateInAssignableUserType) ToPointer() *StepAPICreateInAssignableUserType {
	return &e
}

func (e *StepAPICreateInAssignableUserType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "APP_AND_EXTERNAL_USERS":
		fallthrough
	case "APP_USERS":
		fallthrough
	case "EXTERNAL_USERS":
		*e = StepAPICreateInAssignableUserType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StepAPICreateInAssignableUserType: %v", v)
	}
}

// StepAPICreateIn - Step (Create)
type StepAPICreateIn struct {
	// Indicates which users are allowed to be assigned this step on a record (defaults to APP_USERS)
	AssignableUserType *StepAPICreateInAssignableUserType `json:"assignableUserType,omitempty"`
	// Whether comments are displayed on a step (defaults to false)
	EnableComments *bool `json:"enableComments,omitempty"`
	// Whether MFA is required for external users to access this step. (defaults to false)
	ExternalUserMfaRequired *bool `json:"externalUserMfaRequired,omitempty"`
	// The name of the step
	Name string `json:"name"`
	// The unique ID of the parent workflow of the step
	WorkflowID string `json:"workflowId"`
	// The x-coordinate of the step in the application builder (must not be less than 0, defaults to 0)
	Xpos *int `json:"xpos,omitempty"`
	// The y-coordinate of the step in the application builder (must not be less than 0, defaults to 0)
	Ypos *int `json:"ypos,omitempty"`
}

func (o *StepAPICreateIn) GetAssignableUserType() *StepAPICreateInAssignableUserType {
	if o == nil {
		return nil
	}
	return o.AssignableUserType
}

func (o *StepAPICreateIn) GetEnableComments() *bool {
	if o == nil {
		return nil
	}
	return o.EnableComments
}

func (o *StepAPICreateIn) GetExternalUserMfaRequired() *bool {
	if o == nil {
		return nil
	}
	return o.ExternalUserMfaRequired
}

func (o *StepAPICreateIn) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *StepAPICreateIn) GetWorkflowID() string {
	if o == nil {
		return ""
	}
	return o.WorkflowID
}

func (o *StepAPICreateIn) GetXpos() *int {
	if o == nil {
		return nil
	}
	return o.Xpos
}

func (o *StepAPICreateIn) GetYpos() *int {
	if o == nil {
		return nil
	}
	return o.Ypos
}
