// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// StepPropertyAPIOutType - The type of the step
type StepPropertyAPIOutType string

const (
	StepPropertyAPIOutTypeOrigin StepPropertyAPIOutType = "ORIGIN"
	StepPropertyAPIOutTypeChain  StepPropertyAPIOutType = "CHAIN"
	StepPropertyAPIOutTypeEnd    StepPropertyAPIOutType = "END"
)

func (e StepPropertyAPIOutType) ToPointer() *StepPropertyAPIOutType {
	return &e
}

func (e *StepPropertyAPIOutType) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "ORIGIN":
		fallthrough
	case "CHAIN":
		fallthrough
	case "END":
		*e = StepPropertyAPIOutType(v)
		return nil
	default:
		return fmt.Errorf("invalid value for StepPropertyAPIOutType: %v", v)
	}
}

// StepPropertyAPIOut - The origin step of the record
type StepPropertyAPIOut struct {
	// The unique ID of this Risk Cloud resource
	ID *string `json:"id,omitempty"`
	// The name of the step
	Name *string `json:"name,omitempty"`
	// Identifies the type of object this data represents
	Object *string `json:"object,omitempty"`
	// The type of the step
	Type *StepPropertyAPIOutType `json:"type,omitempty"`
}

func (o *StepPropertyAPIOut) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *StepPropertyAPIOut) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *StepPropertyAPIOut) GetObject() *string {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *StepPropertyAPIOut) GetType() *StepPropertyAPIOutType {
	if o == nil {
		return nil
	}
	return o.Type
}
