// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// UserPropertyAPIOut - The creator of the record
type UserPropertyAPIOut struct {
	// The email of the user
	Email *string `json:"email,omitempty"`
	// The unique ID of this Risk Cloud resource
	ID *string `json:"id,omitempty"`
	// The name of the user
	Name *string `json:"name,omitempty"`
	// Identifies the type of object this data represents
	Object *string `json:"object,omitempty"`
}

func (o *UserPropertyAPIOut) GetEmail() *string {
	if o == nil {
		return nil
	}
	return o.Email
}

func (o *UserPropertyAPIOut) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *UserPropertyAPIOut) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *UserPropertyAPIOut) GetObject() *string {
	if o == nil {
		return nil
	}
	return o.Object
}
