// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkflowPropertyAPIOut - The parent workflow of the step
type WorkflowPropertyAPIOut struct {
	// The unique ID of this Risk Cloud resource
	ID *string `json:"id,omitempty"`
	// The name of the workflow
	Name *string `json:"name,omitempty"`
	// Identifies the type of object this data represents
	Object *string `json:"object,omitempty"`
	// The prefix to be used in the name of every record created from this workflow
	RecordPrefix *string `json:"recordPrefix,omitempty"`
}

func (o *WorkflowPropertyAPIOut) GetID() *string {
	if o == nil {
		return nil
	}
	return o.ID
}

func (o *WorkflowPropertyAPIOut) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *WorkflowPropertyAPIOut) GetObject() *string {
	if o == nil {
		return nil
	}
	return o.Object
}

func (o *WorkflowPropertyAPIOut) GetRecordPrefix() *string {
	if o == nil {
		return nil
	}
	return o.RecordPrefix
}
