// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkflowAPIUpdateIn - Workflow (Update)
type WorkflowAPIUpdateIn struct {
	// The name of the workflow
	Name *string `json:"name,omitempty"`
	// The prefix to be used in the name of every record created from this workflow
	RecordPrefix *string `json:"recordPrefix,omitempty"`
	// The x-coordinate of the workflow in the application builder (must not be less than 0)
	Xpos *int `json:"xpos,omitempty"`
	// The y-coordinate of the workflow in the application builder (must not be less than 0)
	Ypos *int `json:"ypos,omitempty"`
}

func (o *WorkflowAPIUpdateIn) GetName() *string {
	if o == nil {
		return nil
	}
	return o.Name
}

func (o *WorkflowAPIUpdateIn) GetRecordPrefix() *string {
	if o == nil {
		return nil
	}
	return o.RecordPrefix
}

func (o *WorkflowAPIUpdateIn) GetXpos() *int {
	if o == nil {
		return nil
	}
	return o.Xpos
}

func (o *WorkflowAPIUpdateIn) GetYpos() *int {
	if o == nil {
		return nil
	}
	return o.Ypos
}
