// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

// Relationship - The type of the relationship between workflows
type Relationship string

const (
	RelationshipOneToOne   Relationship = "OneToOne"
	RelationshipOneToMany  Relationship = "OneToMany"
	RelationshipManyToOne  Relationship = "ManyToOne"
	RelationshipManyToMany Relationship = "ManyToMany"
)

func (e Relationship) ToPointer() *Relationship {
	return &e
}

func (e *Relationship) UnmarshalJSON(data []byte) error {
	var v string
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	switch v {
	case "OneToOne":
		fallthrough
	case "OneToMany":
		fallthrough
	case "ManyToOne":
		fallthrough
	case "ManyToMany":
		*e = Relationship(v)
		return nil
	default:
		return fmt.Errorf("invalid value for Relationship: %v", v)
	}
}

// WorkflowMapAPICreateIn - Workflow Map (Create)
type WorkflowMapAPICreateIn struct {
	// The unique ID of the source workflow of the workflow map relationship
	From string `json:"from"`
	// The type of the relationship between workflows
	Relationship Relationship `json:"relationship"`
	// The unique ID of the destination workflow of the workflow map relationship
	To string `json:"to"`
}

func (o *WorkflowMapAPICreateIn) GetFrom() string {
	if o == nil {
		return ""
	}
	return o.From
}

func (o *WorkflowMapAPICreateIn) GetRelationship() Relationship {
	if o == nil {
		return Relationship("")
	}
	return o.Relationship
}

func (o *WorkflowMapAPICreateIn) GetTo() string {
	if o == nil {
		return ""
	}
	return o.To
}
