// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// WorkflowAPICreateIn - Workflow (Create)
type WorkflowAPICreateIn struct {
	// The unique ID of the parent application of the workflow
	ApplicationID string `json:"applicationId"`
	// The name of the workflow
	Name string `json:"name"`
	// The prefix to be used in the name of every record created from this workflow
	RecordPrefix string `json:"recordPrefix"`
	// The x-coordinate of the workflow in the application builder (must not be less than 0, defaults to 0)
	Xpos *int `json:"xpos,omitempty"`
	// The y-coordinate of the workflow in the application builder (must not be less than 0, defaults to 0)
	Ypos *int `json:"ypos,omitempty"`
}

func (o *WorkflowAPICreateIn) GetApplicationID() string {
	if o == nil {
		return ""
	}
	return o.ApplicationID
}

func (o *WorkflowAPICreateIn) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *WorkflowAPICreateIn) GetRecordPrefix() string {
	if o == nil {
		return ""
	}
	return o.RecordPrefix
}

func (o *WorkflowAPICreateIn) GetXpos() *int {
	if o == nil {
		return nil
	}
	return o.Xpos
}

func (o *WorkflowAPICreateIn) GetYpos() *int {
	if o == nil {
		return nil
	}
	return o.Ypos
}
